# Generated by Django 5.1.4 on 2025-01-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticad', '0002_profile_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='behance',
            field=models.URLField(blank=True, help_text='URL do perfil no Behance', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='deviantart',
            field=models.URLField(blank=True, help_text='URL do perfil no DeviantArt', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='dribbble',
            field=models.URLField(blank=True, help_text='URL do perfil no Dribbble', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.URLField(blank=True, help_text='URL do perfil no Facebook', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fivehundredpx',
            field=models.URLField(blank=True, help_text='URL do perfil no 500px', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='flickr',
            field=models.URLField(blank=True, help_text='URL do perfil no Flickr', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.URLField(blank=True, help_text='URL do perfil no GitHub', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.URLField(blank=True, help_text='URL do perfil no Instagram', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(blank=True, help_text='URL do perfil no LinkedIn', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pinterest',
            field=models.URLField(blank=True, help_text='URL do perfil no Pinterest', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tiktok',
            field=models.URLField(blank=True, help_text='URL do perfil no TikTok', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.URLField(blank=True, help_text='URL do perfil no Twitter', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='unsplash',
            field=models.URLField(blank=True, help_text='URL do perfil no Unsplash', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='vimeo',
            field=models.URLField(blank=True, help_text='URL do perfil no Vimeo', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='youtube',
            field=models.URLField(blank=True, help_text='URL do canal no YouTube', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, help_text="Outros links personalizados ou redes sociais emergentes. Exemplo: {'medium': 'https://medium.com/@username', 'vimeo': 'https://vimeo.com/username'}"),
        ),
    ]
