# Generated by Django 5.1.4 on 2025-01-10 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticad', '0003_profile_behance_profile_deviantart_profile_dribbble_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='social_links',
        ),
    ]
