# Generated by Django 5.1.4 on 2025-01-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticad', '0004_remove_profile_social_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='folder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
