# Generated by Django 5.1.4 on 2025-01-12 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticad', '0006_alter_media_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('is_registered', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='group',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='media',
            name='watermark_applied',
        ),
        migrations.AlterField(
            model_name='media',
            name='file_path',
            field=models.ImageField(max_length=255, upload_to='media_files/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='autenticad.gallery'),
        ),
        migrations.AddField(
            model_name='media',
            name='directory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='autenticad.directory'),
        ),
    ]
