# Generated by Django 5.1.4 on 2025-01-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticad', '0007_directory_remove_gallery_group_remove_gallery_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watermark',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
