# Generated by Django 5.1.4 on 2025-01-13 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticad', '0009_watermark_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autenticad.directory'),
        ),
    ]
