# Generated by Django 5.1.4 on 2025-01-13 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticad', '0010_gallery_directory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='watermark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autenticad.watermark'),
        ),
    ]
