# Generated by Django 5.1.4 on 2025-01-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticad', '0011_alter_gallery_watermark'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='has_finalized_gallery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gallery',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
