# Generated by Django 5.1.4 on 2025-01-14 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticad', '0012_directory_has_finalized_gallery_gallery_is_finalized'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Grupo de usuários que poderão visualizar esta galeria.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
    ]
